% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% File: m3makefile
% Last modified on Tue Jan 24 13:10:54 PST 1995 by kalsow
%      modified on Wed Jun  2 12:06:33 PDT 1993 by muller

% remove_m3_option ("-gui")
% m3_option ("-times")

import ("libm3")
import ("m3quake")
import ("libcm3")

implementation ("Main")

build_standalone () %-- we don't want to depend on the shared libraries...

Program ("cm3")
