% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Aug 26 12:59:55 PDT 1993 by kalsow  
%      modified on Thu Jun 17 19:25:19 PDT 1993 by harrison
%      modified on Mon Apr 26 13:39:39 PDT 1993 by mcjones
%      modified on Fri Apr 16 18:04:35 PDT 1993 by meehan
%      modified on Thu Feb 18 08:55:48 PST 1993 by mjordan

Generic_module("List")
Generic_module("ListSort")
HtmlGenericInterface("List")
HtmlGenericInterface("ListSort")

template ("list")

List ("Int",  "Integer")
List ("Ref",  "Refany")
List ("Text", "Text")

TransientList ("Atom", "Atom")
TransientList ("IntTransient",  "Integer")
TransientList ("RefTransient",  "RefanyTransient")
TransientList ("TextTransient", "Text")

List_sort ("Int",  "Integer")
List_sort ("Ref",  "Refany")
List_sort ("Text", "Text")

TransientList_sort ("Atom", "Atom")
TransientList_sort ("IntTransient",  "Integer")
TransientList_sort ("RefTransient",  "RefanyTransient")
TransientList_sort ("TextTransient", "Text")
