% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Jan 17 15:59:10 PST 1995 by kalsow 
%      modified on Fri Nov  5 16:41:57 PST 1993 by detlefs
%      modified on Mon Jan 18 19:09:20 PST 1993 by muller

%
%  To rebuild the parser or lexer tables, cd to this
%  directory and run the standard make.
%

h_source ("lex.yy") % it's really a .c file that matters
c_source ("y.tab")
import_lib ("l", "/usr/lib")




