/* Copyright (C) 1996, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Fri May 24 08:43:02 PDT 1996 by mcjones */

implementation("LecternClientWin32")
implementation("LecternServerWin32")


readonly proc simple_c_program(nm) is
  local SRCFILE = path_of(nm & ".c")
  local EXEFILE = nm & ".EXE"
  local ret = 0
  local cmd = [ DEV_BIN & "cl", "/Fe" & EXEFILE, SRCFILE ]

  if stale(EXEFILE, SRCFILE)
    write (cmd, "\n")
    ret = exec (cmd)
    if not equal(ret, 0) error("command failed with error code: ", ret) end
  end

  deriveds(EXEFILE, [nm & ".OBJ"])
end
%simple_c_program("LecternClient")
%BindExport("LecternClient")
