# Copyright 1989 Digital Equipment Corporation.
# Distributed only by permission.
# Last modified on Fri Sep 13 17:52:52 1991 by kalsow
#      modified on Wed Jun  5 03:20:17 1991 by muller
#      modified on Thu Feb  7 12:23:03 PST 1991 by stolfi
#****************************************************************
# Caller must define the environment vars 
#   ${CPU_TYPE} ${M3COMPILER}

#*************************************************************************

M3D = /udir/kalsow/m3

# M3 = $(M3D)/m3driver-2/mips/m3xx
M3 = $(M3D)/m3driver-2/mips/m3xx -Y0.$(M3D)/m3compiler/mips/m3compiler.
# M3 = $(M3D)/m3driver-2/mips/m3xx -Y0.$(M3D)/m3c/mips/m3compiler.

LIBS = -nostd $(M3D)/m3-2.mips/libm3.a -lm

M3FLAGS = -g -w1 -make -keep -commands $(DEFPATH) $(LIBS)

# ***************************************************************
# Entry to bring the package up to date ("all" must be first)

all: test

test: ; $(M3) $(M3FLAGS) -o Main *.[im]3

# ***************************************************************
# Standard entries to remove files from the directories
#
#    tidy    -- eliminate garbage files
#    scratch -- delete derived files in preparation for rebuild

tidy:         ; /bin/rm -f ,* .,* *~ .emacs_[0-9]* core a.out m3_* m3*.c
scratch: tidy ; /bin/rm -f *.io *.mo *.ic *.mc
  
# *****************************************************************


