% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description. 
%
% Last modified on Sat Feb 25 09:39:05 PST 1995 by kalsow  

import ("libm3")
import ("m3quake")
import ("tempfiles")
import ("m3templates")
import ("m3config")

implementation ("Main")

HtmlFile("index")

Program ("m3where")


