% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for network object stub generator
%
% Last modified on Mon Jan 23 14:47:21 PST 1995 by kalsow
%      modified on Thu May 12 16:03:14 PDT 1994 by wobber


import("libm3")
import("m3tk")

interface("ValueProc")
interface("Protocol")

module("TypeNames")
module("Type")
module("Value")
module("AstToVal")
module("AstToType")
module("StubCode")
module("CodeForType")
module("ModuleStubCode")
module("IntfStubCode")
module("StubGenTool")
module("StubUtils")
module("FRefRefTbl")

implementation("Main")

option("standalone","T")

Program("stubgen")

if "TRUE"
  local stubgenv1 = "stubgenv1" & NAMING_CONVENTIONS[20]
  link_file ("stubgen" & NAMING_CONVENTIONS[20], stubgenv1)
  install_derived (stubgenv1)
  install_link_to_derived (stubgenv1, BIN_INSTALL)
end

ManPage("stubgen","1")

