% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Feb 23 14:02:51 PST 1995 by kalsow

if defined ("_all")
  local src = path_of ("report_coverage.c")
  local obj = "report_coverage" & OBJ_ext
  local cmd = [ CC, "-c", "-g", src ]
  local ret = 0
  if stale (obj, src)
    write (cmd)
    ret = exec (cmd)
    if not equal(ret, 0) error("command failed with error code: ", ret) end
  end
end
LibdExport ("report_coverage.o")

if defined ("_all")
  local src = path_of ("analyze_coverage.c")
  local pgm = program_name ("analyze_coverage")
  local cmd = [ CC, "-I../src", "-g", "-o", pgm, src ]
  local ret = 0
  if stale (pgm, src)
    write (cmd)
    ret = exec (cmd)
    if not equal(ret, 0) error("command failed with error code: ", ret) end
  end
end
BindExport ("analyze_coverage")

ManPage ("analyze_coverage", 1)
