
readonly proc SourceFile (nm) is
  ship_source(nm)
end

SourceFile("catalog")
SourceFile("HTML4.soc")
SourceFile("HTML4.dtd")
SourceFile("HTMLmisc.ent")
SourceFile("HTMLsym.ent")
SourceFile("ISOlat1.ent")
SourceFile("Math.ent")
SourceFile("HTML32.dcl")
SourceFile("HTML32.dtd")
SourceFile("HTML32.soc")
SourceFile("linuxdoc.dtd")
SourceFile("linuxdoc.soc")
SourceFile("linuxdocadd.dtd")
