% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description. 
%
% Last modified on Sat Feb 25 09:39:05 PST 1995 by kalsow  

import ("libm3")
import ("m3quake")
import ("m3templates")
import ("m3config")
import("m3doc")

implementation ("Main")

HtmlFile("index")

%option("standalone","T")

Program ("m3ship")


