\input texinfo        @c                    -*- Texinfo -*-
@setfilename lynx.info
@settitle LynxOS 2.2 Development

@finalout
@setchapternewpage off
@iftex
@raggedbottom
@global@parindent=0pt
@end iftex

@titlepage
@title LynxOS Development
@subtitle With the Cygnus Developer's Kit
@subtitle for LynxOS 2.2
@sp 4
@subtitle March 1994
@author Cygnus Support
@page

@vskip 0pt plus 1filll
Copyright @copyright{} 1993, 1994 Cygnus Support

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.
@end titlepage

@ifinfo
@format
START-INFO-DIR-ENTRY
* LynxOS 2.2: (lynx.info).         LynxOS 2.2 Development
END-INFO-DIR-ENTRY
@end format

Copyright (c) 1993, 1994 Cygnus Support

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.

@node Top
@top LynxOS 2.2 Development with the Cygnus Developer's Kit

@display
@strong{Cygnus Support}
March 1994
@end display

This note is a summary of the Cygnus Developer's Kit special features
for systems running LynxOS.
@end ifinfo

@include lynx-chap.texi

@page
@contents
@c second page break makes sure right-left page alignment works right
@c with a one-page toc, even though we don't have setchapternewpage odd.
@page
@w{ }
@bye



