% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Apr  5 17:12:45 PDT 1995 by mhb   
%      modified on Fri Sep 16 13:44:30 PDT 1994 by bharat
%      modified on Wed Mar 23 14:11:53 1994 by luca

resource ("volib.obl")
resource("vorestrict.obl")
resource ("templates.obl")
resource ("vowidgets.obl")
resource ("vocheckpt.obl")

bundle ("VORunBundle")

import("obliqlibm3")
import("obliqlibui")
import("obliq")
implementation("Main")

program("vorun")

% create vostart

if defined ("_all")
  local script = path_of ("vostart")
  if stale ("vostart", script)
    % build a version of vostart bound to the current /bin directory
    > "vostart" in  write ("#! ", BIN_USE & SL & "vorun -r", CR)  end
    write ("making vostart")
    local ret = exec ([ "cat", script ] , ["", ">>vostart" ] )
    if not equal(ret, 0) 
      error ("coulnd't create the script! (error code: ", ret, ")") end      
    ret = exec ([ "chmod", "+x", "vostart" ])
    if not equal(ret, 0) 
      error ("chmod failed on vostart with error code: ", ret) end
  end
  deriveds ("vostart", [NAMING_CONVENTIONS[17]])
end
% BindExport ("vostart")
