import("libm3")
import("GrasCommon")

include_dir("RuleTypes")
include_dir("EventHandler")

transientSequence("EventHandler", "EventHandler")
transientTable("CardEventHandler", "Cardinal", "EventHandler")

Module("EventDetector")
transientSequence("EventDetector", "EventDetector")
transientTable("CardEventDetectorSeq", "Cardinal", "EventDetectorSeq")

module("LocalRuleHandler")
include_dir("RemoteRuleHandler")
Module("RuleEngine")

Library("RuleEngine")
