
import("m3doc")

HtmlFile("index")
HtmlFile("gc")
HtmlFile("m3args")
HtmlFile("pragmas")
HtmlFile("restrictions")
HtmlFile("runtime")
HtmlFile("scheduler")
HtmlFile("signals")

include_dir("linking")

OtherPackage("m3compiler")
