% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Aug 26 11:55:48 PDT 1993 by kalsow
%      modified on Mon Apr 26 13:38:32 PDT 1993 by mcjones

Generic_interface("TableRep")
Generic_interface("TableTransientRep")
Generic_module("Table")
HtmlGenericInterface("Table")

template ("table")

TransientTable ("AtomAtom", "Atom", "Atom")
TransientTable ("AtomInt",  "Atom", "Integer")
TransientTable ("AtomRef",  "Atom", "Refany")
TransientTable ("AtomRefTransient",  "Atom", "RefanyTransient")
TransientTable ("AtomText", "Atom", "Text")

Table ("IntInt",  "Integer", "Integer")
Table ("IntRef",  "Integer", "Refany")
Table ("IntText", "Integer", "Text")

TransientTable ("IntAtom", "Integer", "Atom")
TransientTable ("IntIntTransient",  "Integer", "Integer")
TransientTable ("IntRefTransient",  "Integer", "RefanyTransient")
TransientTable ("IntTextTransient", "Integer", "Text")

Table ("RefInt",  "Refany", "Integer")
Table ("RefRef",  "Refany", "Refany")
Table ("RefText", "Refany", "Text")

TransientTable ("RefAtom", "Refany", "Atom")
TransientTable ("RefAtomTransient", "RefanyTransient", "Atom")
TransientTable ("RefIntTransient",  "RefanyTransient", "Integer")
TransientTable ("RefRefTransient",  "RefanyTransient", "RefanyTransient")
TransientTable ("RefTextTransient", "RefanyTransient", "Text")

Table ("TextInt",  "Text", "Integer")
Table ("TextRef",  "Text", "Refany")
Table ("TextText", "Text", "Text")

TransientTable ("TextAtom", "Text", "Atom")
TransientTable ("TextIntTransient",  "Text", "Integer")
TransientTable ("TextRefTransient",  "Text", "RefanyTransient")
TransientTable ("TextTextTransient", "Text", "Text")
