/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Mon Jun  3 14:10:23 PDT 1996 by mcjones */

implementation("LecternClientPosix")
implementation("LecternServerPosix")

readonly proc simple_c_program(nm) is
  local SRCFILE = path_of(nm & ".c")
  local EXEFILE = nm
  local ret = 0
  local cmd = [ CC, "-o", EXEFILE, SRCFILE ]

  if stale(EXEFILE, SRCFILE)
    write(cmd, "\n")
    ret = exec (cmd)
    if not equal(ret, 0) error("command failed with error code: ", ret) end
  end

  deriveds(EXEFILE, no_extension)
end
simple_c_program("LecternClient")
BindExport("LecternClient")
