
import("libm3")
import("m3coco")

coco_c("HTML")
coco_c("calc")
coco_c("cdecl")
coco_c("mod2")
coco_c("umbriel2")

% they contain errors but I keep them
% to check the behaviour of m3coco
coco_c("Mod3")
coco_c("adacs")
coco_c("c")
coco_c("clang1")
coco_c("clang2")
coco_c("cminus")
coco_c("cminus1")
coco_c("microada")
coco_c("oberon")
coco_c("pascal")
coco_c("pimmod2")
coco_c("umbriel1")
