import("libm3")

template("coco")

resource("compiler.frm")
resource("scanner.frm")
resource("parser.frm")
resource("interface.frm")
bundle("CocoFrames")

module("Frame")

module("CRA")
module("CRT")
module("CRX")

module("CR")
implementation("CRP")
implementation("CRS")

Program("m3coco")
