%import("GrasGraphs")
import("mgkit")
import("formsvbt")
import("HiGRAS")
import("GrasParams")

resource("indextrees.fv")
resource("indextree.fv")
bundle("GDForms")

implementation("GraphDump")
Program("graphdump")

ManPage("graphdump", "1")
