/* Copyright (C) 1996, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Fri May 24 08:43:02 PDT 1996 by mcjones */

implementation("LecternClientWin32")
implementation("LecternServerWin32")

readonly proc simple_c_program(nm) is
  local src = path_of (nm & ".c")
  local obj = nm & NAMING_CONVENTIONS[13] % .o
  local pgm = nm & NAMING_CONVENTIONS[20] % .exe
  local ret = 0

  if stale(pgm, src)
    ret = m3_compile_c(src,obj,[])
    if not equal(ret, 0) error("command failed with error code: ", ret) end
    ret = m3_link(pgm,[obj],[])
    if not equal(ret, 0) error("command failed with error code: ", ret) end
  end

  deriveds(pgm, [NAMING_CONVENTIONS[17]])
end

%setCommands("","")
%simple_c_program("LecternClient")
%BindExport("LecternClient")
