
import("synloc")
import("obliqrt")
import("obliqlibm3")
import("obliq")
import("sgml")
import("m3doc")

module("ObLibTbl")

implementation("Main")

resource_named("startup","sgml.obl")

bundle("SGMLBundle")

HtmlFile("index")

Program("obliq-sgml")

