% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov 22 07:56:33 PST 1994 by kalsow

import ("m3middle")

if equal(TARGET,"LINUXELF")
  include_dir("linux")
elsif equal(TARGET,"NT386")
  include_dir("nt")
end

Library ("m3objfile")
