
import("formsvbt")
import("HiGRAS")
import("GrasParams")

resource("TreePanel.fv")
bundle("TreeBundle")

interface("TreeScheme")
module("Command")
module("Panel")
implementation("Tree")
Program("Tree")
