

import("libm3")
import("formsvbt")
import("m3config")
import("m3doc")

implementation("Main")

module("Ide")
module("IdeUtil")
%module("IdeHTTP")
%module("IdeSearch")

Gnuemacs("m3ide")
Gnuemacs("m3menu")
Gnuemacs("m3process")
Gnuemacs("m3setup")
HtmlFile("index")

Program("m3ide")

