% Copyright 1993 Digital Equipment Corporation.
% Distributed only by permission.
%
% Last modified on Fri Oct 28 15:38:19 PDT 1994 by kalsow
%      modified on Fri Sep 16 19:16:35 PDT 1994 by heydon

Generic_module    ("PQueue")
Generic_interface ("PQueueRep")
Generic_interface ("PQueueTransientRep")
template          ("pqueue")

%% standard instances
Pqueue ("Int",  "Integer")
Pqueue ("Ref",  "Refany")
Pqueue ("Text", "Text")

TransientPqueue ("Atom", "Atom")
TransientPqueue ("IntTransient",  "Integer")
TransientPqueue ("RefTransient",  "RefanyTransient")
TransientPqueue ("TextTransient", "Text")
