
import("libm3")
import("m3doc")

HtmlFile("index")
HtmlTextFile("intBsLines.txt")
HtmlTextFile("intBsFiles.txt")
HtmlTextFile("intBsFiles2.txt")
HtmlTextFile("modBsLines.txt")
HtmlTextFile("modBsFiles.txt")
HtmlTextFile("modBsFiles2.txt")
HtmlTextFile("tex2ht.txt")

implementation ("Main")

Program ("m3textohtml")
