% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Oct 11 13:54:10 PDT 1995 by najork
%      modified on Wed Jun 14 13:41:11 PDT 1995 by kalsow
%
% Contributed by Harry George (hgeorge@eskimo.com), 5/16/95

if PLATFORM_SUPPORTS_MOTIF
  import_Motif ()
  import ("X11")

  Interface ("IntrinsicP")
  Module    ("Xmacro")
  Module    ("Xm")
  Module    ("XmC")
  Module    ("XmN")
  Module    ("Xmw")

  Library ("m3motif")
end
