import			("set")

% *** common stuff ***
mkTransientSet		("ServedClient", "ServedClient")
transientTable		("ServedClientRefTransient", "ServedClient", "RefanyTransient")
mkTransientSetDef	("ServedClient", "ServedClient")

% *** server lock entry ***
module			("ServerLockEntry")

% *** scheduled server page ***
transientTable		("BaseServerLock", "ServedClient", "ServerLockEntry")
module			("ServerLockTable")
module			("ScheduledServerPage")

% *** scheduled server file ***
Module			("BaseScheduledServerFile")
interface		("InternalBaseScheduledServerFile")
transientTable		("ScheduledServerPage", "Cardinal", "ScheduledServerPage")
Module			("ScheduledServerFile")
interface		("InternalScheduledServerFile")

% *** scheduled server resource ***
Module			("BaseScheduledServerResource")
interface		("InternalBaseScheduledServerResource")
transientTable		("ScheduledServerFile", "Text", "ScheduledServerFile")
Module			("ScheduledServerResource")
interface		("InternalScheduledServerResource")

% *** server scheduler ***
module			("BaseServerScheduler")
transientTable		("ScheduledServerResource","Text","ScheduledServerResource")
Module			("ServerScheduler")

% *** deadlock detection ***
module			("ServerWaitEntry")
transientTable		("ServerWait", "ServedClient", "ServerWaitEntry")
module			("WaitForGraph")
module			("DeadlockDetection")
