import_sys_lib("DB")

c_includes += "-I" & DB_ROOT & "include"
c_source("BerkeleyDB")
interface("BerkeleyDB")

interface ("DB")

interface ("InternalDatabase")
interface ("InternalTransaction")
interface ("InternalDBPage")

implementation ("Database")
implementation ("Transaction")
implementation ("DBPage")
