import ("BerkeleyDB")

interface ("DB")

interface ("InternalDatabase")
interface ("InternalTransaction")
interface ("InternalDBPage")

implementation ("Database")
implementation ("Transaction")
implementation ("DBPage")
