% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

module ("PklTipeMap")
module ("ConvertPacking")
interface ("PklAction")
interface ("PickleRd")
transientSequence ("PklAction", "PklAction")
module ("PackingTypeCode")
transientTable ("Packing", "PackingTypeCode", "RefanyTransient")
module ("BuiltinSpecials")

Module ("Pickle")
Module ("PickleStubs")
