.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Thu Jun  2 16:46:39 PDT 1994 by kalsow 
.\"      modified on Wed May 19 11:36:32 PDT 1993 by mjordan
.\"      modified on Tue Oct 13 16:39:21 PDT 1992 by muller
.\"      modified on Tue Sep 22 08:36:57 PDT 1992 by mhb
.nh
.TH M3BUILD 1
.SH NAME
m3build \- Modula-3 builder

.\"------------------------------------------------------------------------
.SH SYNTAX
.B m3build 
[options] [target ...]

.\"------------------------------------------------------------------------
.SH DESCRIPTION

.PP
\fIm3build\fP
is a program that builds Modula-3 libraries and programs.
.PP
Its primary description is at URL:
.IP
.nf
http://www.research.digital.com/SRC/modula-3/html/m3build/m3build.html
.PP

.\"------------------------------------------------------------------------
.SH SEE ALSO
.BR m3where (1),
.BR m3ship (1).

.SH AUTHOR OF OBJECT
     Mick Jordan, Stephen Harrison, Bill Kalsow

.SH AUTHOR OF DOCUMENTATION
     Bill Kalsow

