.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Thu Jun  2 16:47:10 PDT 1994 by kalsow 
.nh
.TH M3SHIP 1
.SH NAME
m3ship \- Modula-3 install operation

.\"------------------------------------------------------------------------
.SH SYNTAX
.B m3ship
[options]

.\"------------------------------------------------------------------------
.SH DESCRIPTION
.PP
\fIm3ship\fP
will ship all the build directories (for different architectural
variants) that exist in a Modula-3 package.
.PP
Its primary description is at URL:
.IP
.nf
http://www.research.digital.com/SRC/modula-3/html/m3ship.html
.PP

.\"------------------------------------------------------------------------
.SH SEE ALSO
.BR m3build (1),
.BR m3where (1),

.SH AUTHOR OF OBJECT
  Eric Muller, Bill Kalsow

.SH AUTHOR OF DOCUMENTATION
  Bill Kalsow


