.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Thu Jun  2 16:47:21 PDT 1994 by kalsow 
.\"      modified on Thu May  6 12:48:23 PDT 1993 by mjordan
.nh
.TH M3WHERE 1
.SH NAME
m3where \- Modula-3 source locator

.\"------------------------------------------------------------------------
.SH SYNTAX
.B m3where 
options [ unit ... ]

.\"------------------------------------------------------------------------
.SH DESCRIPTION

.PP
\fIm3where\fP
is a program that locates Modula-3 source files, relative to a
particular program or library package.
.PP
Its primary description is at URL:
.IP
.nf
http://www.research.digital.com/SRC/modula-3/html/m3where.html
.PP


.\"------------------------------------------------------------------------
.SH SEE ALSO
.BR m3build (1),
.BR m3ship (1).

.SH AUTHOR OF OBJECT
     Mick Jordan

.SH AUTHOR OF DOCUMENTATION
     Mick Jordan

